steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--no-cache',
    '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/rop-frontend:latest',
    '--build-arg', 'REACT_APP_API_BASE_URL=${_REACT_APP_API_BASE_URL}',
    '.'
  ]
images:
- 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/app/rop-frontend:latest'
substitutions:
  _REACT_APP_API_BASE_URL: ''  # デフォルト空（ビルド時に渡す）