steps:
  # バックエンドイメージのビルドとプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rop-backend', './backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rop-backend']

  # フロントエンドイメージのビルドとプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rop-frontend', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rop-frontend']

  # バックエンドをCloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rop-backend'
      - '--image=gcr.io/$PROJECT_ID/rop-backend'
      - '--region=asia-northeast1'  # お好みのリージョンに変更
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--set-env-vars=STORAGE_BUCKET_NAME=rop-classify-files,USE_CLOUD_STORAGE=true'

  # フロントエンドをCloud Runにデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rop-frontend'
      - '--image=gcr.io/$PROJECT_ID/rop-frontend'
      - '--region=asia-northeast1'  # お好みのリージョンに変更
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--set-env-vars=REACT_APP_API_BASE_URL=$(gcloud run services describe rop-backend --region=asia-northeast1 --format="value(status.url)")'

images:
  - 'gcr.io/$PROJECT_ID/rop-backend'
  - 'gcr.io/$PROJECT_ID/rop-frontend'